<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Stateful Domains
    |--------------------------------------------------------------------------
    |
    | Requests from the following domains / hosts will receive session cookies
    | when using Sanctum's stateful authentication.
    |
    */

    'stateful' => explode(',', env('SANCTUM_STATEFUL_DOMAINS', sprintf(
        '%s%s',
        'localhost,localhost:3000,127.0.0.1:3000,::1',
        env('APP_URL') ? ','.parse_url(env('APP_URL'), PHP_URL_HOST) : ''
    ))),

    /*
    |--------------------------------------------------------------------------
    | Sanctum Guards
    |--------------------------------------------------------------------------
    |
    | This array contains the authentication guards that will be checked when
    | Sanctum is trying to authenticate a request. If none of these guards
    | are able to authenticate the request, Sanctum will return a 401 error.
    |
    */

    'guard' => ['web'],

    /*
    |--------------------------------------------------------------------------
    | Expiration Minutes
    |--------------------------------------------------------------------------
    |
    | This value controls the number of minutes until an issued token will be
    | considered expired. If this value is null, personal access tokens do not
    | expire.
    |
    */

    'expiration' => null,

    /*
    |--------------------------------------------------------------------------
    | Token Prefix
    |--------------------------------------------------------------------------
    |
    | This value is used to prefix the personal access token generated by
    | Sanctum. This can be useful for easily identifying tokens in logs or
    | other output.
    |
    */

    'token_prefix' => '',

    /*
    |--------------------------------------------------------------------------
    | Personal Access Token Hashing
    |--------------------------------------------------------------------------
    |
    | By default, personal access tokens are hashed using the SHA-256 algorithm.
    | You may customize the hashing algorithm by defining the `hash_algorithm`
    | configuration option. Supported algorithms are those supported by the
    | `hash()` function.
    |
    */

    'hash_algorithm' => 'sha256',

    /*
    |--------------------------------------------------------------------------
    | Personal Access Token Expiration
    |--------------------------------------------------------------------------
    |
    | This value controls the number of minutes until an issued token will be
    | considered expired. If this value is null, personal access tokens do not
    | expire.
    |
    */

    'personal_access_token_expiration' => null,

];