<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class AdAccount extends Model
{
    protected $fillable = [
        'business_manager_id',
        'account_id',
        'fb_ad_account_id',
        'fb_account_id',
        'pixel_id',
        'owner_account',
        'shared_accounts',
        'name',
        'status',
        'spend',
        'currency',
        'impressions',
        'clicks',
        'balance',
        'outstanding_balance',
        'available_credit',
        'billing_threshold',
        'daily_spending_limit',
        'account_spending_limit',
        'automation_mode',
        'manual_mode',
        'token',
        'useragent',
        'proxy',
        'cookie',
        'cookie_raw',
        'cookie_c_user',
        'cookie_xs',
        'cookie_datr',
        'notify_balance_threshold',
        'notify_cooldown_minutes',
        'notify_moderation',
        'notify_cabinet_status',
        'notify_billing',
        'fetch_boosted_posts',
        'fetch_dark_posts',
        'fetch_lead_forms',
        'monitor_impressions',
        'monitor_clicks',
        'monitor_budget',
        'monitor_reach',
        'monitor_engagement',
        'payment_method',
        'payment_method_count',
        'card_status',
        'card_expiration',
        'auto_pay',
        'manual_pay',
        'billing_notifications',
        'country',
        'vat_id',
        'today_spend',
        'yesterday_spend',
        'daily_budget',
        'lifetime_budget',
        'remaining_spend',
        'review_feedback',
        'policy_violations',
        'notification_count',
        'account_health',
        'delivery_issues',
        'applied_auto_rules',
        'auto_comment',
        'restricted',
        'unsettled',
        'pending_review',
        'appeal_submitted',
        'review_result',
        'metadata',
    ];

    protected $casts = [
        'spend' => 'decimal:2',
        'impressions' => 'integer',
        'clicks' => 'integer',
        'balance' => 'decimal:2',
        'outstanding_balance' => 'decimal:2',
        'available_credit' => 'decimal:2',
        'billing_threshold' => 'decimal:2',
        'daily_spending_limit' => 'decimal:2',
        'account_spending_limit' => 'decimal:2',
        'automation_mode' => 'string',
        'manual_mode' => 'boolean',
        'shared_accounts' => 'array',
        'notify_balance_threshold' => 'decimal:2',
        'notify_cooldown_minutes' => 'integer',
        'notify_moderation' => 'boolean',
        'notify_cabinet_status' => 'boolean',
        'notify_billing' => 'boolean',
        'fetch_boosted_posts' => 'boolean',
        'fetch_dark_posts' => 'boolean',
        'fetch_lead_forms' => 'boolean',
        'monitor_impressions' => 'boolean',
        'monitor_clicks' => 'boolean',
        'monitor_budget' => 'boolean',
        'monitor_reach' => 'boolean',
        'monitor_engagement' => 'boolean',
        'payment_method_count' => 'integer',
        'auto_pay' => 'boolean',
        'manual_pay' => 'boolean',
        'billing_notifications' => 'boolean',
        'today_spend' => 'decimal:2',
        'yesterday_spend' => 'decimal:2',
        'daily_budget' => 'decimal:2',
        'lifetime_budget' => 'decimal:2',
        'remaining_spend' => 'decimal:2',
        'policy_violations' => 'integer',
        'notification_count' => 'integer',
        'applied_auto_rules' => 'array',
        'auto_comment' => 'boolean',
        'restricted' => 'boolean',
        'unsettled' => 'boolean',
        'pending_review' => 'boolean',
        'appeal_submitted' => 'boolean',
        'metadata' => 'array',
        'cookie' => 'encrypted',
        'cookie_raw' => 'encrypted',
        'cookie_c_user' => 'encrypted',
        'cookie_xs' => 'encrypted',
        'cookie_datr' => 'encrypted',
    ];

    public function businessManager(): BelongsTo
    {
        return $this->belongsTo(BusinessManager::class);
    }
}
