<?php

namespace App\Http\Resources;

use Illuminate\Http\Resources\Json\JsonResource;

class AdAccountResource extends JsonResource
{
    public function toArray($request): array
    {
        return [
            'id' => $this->id,
            'account_id' => $this->account_id,
            'fb_ad_account_id' => $this->fb_ad_account_id,
            'fb_account_id' => $this->fb_account_id,
            'pixel_id' => $this->pixel_id,
            'owner_account' => $this->owner_account,
            'shared_accounts' => $this->shared_accounts,
            'name' => $this->name,
            'status' => $this->status,
            'spend' => (float) $this->spend,
            'currency' => $this->currency,
            'impressions' => (int) $this->impressions,
            'clicks' => (int) $this->clicks,
            'balance' => (float) $this->balance,
            'outstanding_balance' => (float) $this->outstanding_balance,
            'available_credit' => (float) $this->available_credit,
            'billing_threshold' => $this->billing_threshold !== null ? (float) $this->billing_threshold : null,
            'daily_spending_limit' => $this->daily_spending_limit !== null ? (float) $this->daily_spending_limit : null,
            'account_spending_limit' => $this->account_spending_limit !== null ? (float) $this->account_spending_limit : null,
            'automation_mode' => $this->automation_mode ?? 'api',
            'manual_mode' => (bool) $this->manual_mode,
            'token' => $this->token,
            'useragent' => $this->useragent,
            'proxy' => $this->proxy,
            'cookie' => $this->cookie,
            'cookie_raw' => $this->cookie_raw,
            'cookie_c_user' => $this->cookie_c_user,
            'cookie_xs' => $this->cookie_xs,
            'cookie_datr' => $this->cookie_datr,
            'notify_balance_threshold' => (float) $this->notify_balance_threshold,
            'notify_cooldown_minutes' => (int) $this->notify_cooldown_minutes,
            'notify_moderation' => (bool) $this->notify_moderation,
            'notify_cabinet_status' => (bool) $this->notify_cabinet_status,
            'notify_billing' => (bool) $this->notify_billing,
            'fetch_boosted_posts' => (bool) $this->fetch_boosted_posts,
            'fetch_dark_posts' => (bool) $this->fetch_dark_posts,
            'fetch_lead_forms' => (bool) $this->fetch_lead_forms,
            'monitor_impressions' => (bool) $this->monitor_impressions,
            'monitor_clicks' => (bool) $this->monitor_clicks,
            'monitor_budget' => (bool) $this->monitor_budget,
            'monitor_reach' => (bool) $this->monitor_reach,
            'monitor_engagement' => (bool) $this->monitor_engagement,
            'payment_method' => $this->payment_method,
            'payment_method_count' => (int) $this->payment_method_count,
            'card_status' => $this->card_status,
            'card_expiration' => $this->card_expiration,
            'auto_pay' => (bool) $this->auto_pay,
            'manual_pay' => (bool) $this->manual_pay,
            'billing_notifications' => (bool) $this->billing_notifications,
            'country' => $this->country,
            'vat_id' => $this->vat_id,
            'today_spend' => (float) $this->today_spend,
            'yesterday_spend' => (float) $this->yesterday_spend,
            'daily_budget' => $this->daily_budget !== null ? (float) $this->daily_budget : null,
            'lifetime_budget' => $this->lifetime_budget !== null ? (float) $this->lifetime_budget : null,
            'remaining_spend' => (float) $this->remaining_spend,
            'review_feedback' => $this->review_feedback,
            'policy_violations' => (int) $this->policy_violations,
            'notification_count' => (int) $this->notification_count,
            'account_health' => $this->account_health,
            'delivery_issues' => $this->delivery_issues,
            'applied_auto_rules' => $this->applied_auto_rules,
            'auto_comment' => (bool) $this->auto_comment,
            'restricted' => (bool) $this->restricted,
            'unsettled' => (bool) $this->unsettled,
            'pending_review' => (bool) $this->pending_review,
            'appeal_submitted' => (bool) $this->appeal_submitted,
            'review_result' => $this->review_result,
            'created_at' => $this->created_at,
        ];
    }
}
